In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [3]:
data = pd.read_csv('movie_bd_v5.csv')
data.head(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,6.3,2015
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015

In [4]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1889 entries, 0 to 1888
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   imdb_id               1889 non-null   object
 1   budget                1889 non-null   int64
 2   revenue               1889 non-null   int64
 3   original_title        1889 non-null   object
 4   cast                  1889 non-null   object
 5   director              1889 non-null   object
 6   tagline               1889 non-null   object
 7   overview              1889 non-null   object
 8   runtime               1889 non-null   int64
 9   genres                1889 non-null   object
 10  production_companies  1889 non-null   object
 11  release_date          1889 non-null   object
 12  vote_average          1889 non-null   float64
 13  release_year          1889 non-null   int64
dtypes: float64(1), int64(4), object(9)
memory usage: 206.7+ KB

# Предобработка

In [6]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

# Adding  new column - Profit
data['profit'] = data['revenue'] - data['budget']


#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [7]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)'
# если ответили верно, можете добавить комментарий со значком "+"

In [8]:
# тут пишем ваш код для решения данного вопроса:
data[data['budget']==data['budget'].max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011,641683000

ВАРИАНТ 2

In [9]:
# можно добавлять разные варианты решения

# 2. Какой из фильмов самый длительный (в минутах)?

In [10]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals'

In [11]:
data[data.runtime == data.runtime.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064

# 3. Какой из фильмов самый короткий (в минутах)?

In [12]:
answers['3'] = 'Winnie the Pooh'

In [13]:
data[data.runtime == data.runtime.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000

# 4. Какова средняя длительность фильмов?

In [14]:
answers['4'] = 109.6585494970884

#### ВАРИАНТ 1

In [15]:
data.runtime.mean()

109.6585494970884

#### ВАРИАНТ 2

In [16]:
data.describe()['runtime']['mean']

109.6585494970884

# 5. Каково медианное значение длительности фильмов?

In [17]:
answers['5'] = 107.0

In [18]:
data['runtime'].median()

107.0

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [19]:
answers['6'] = 'Avatar'

In [20]:
# лучше код получения столбца profit вынести в Предобработку что в начале
data[data.profit == data.profit.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

# 7. Какой фильм самый убыточный?

In [21]:
answers['7'] = 'The Lone Ranger'

In [22]:
data[data.profit == data.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [23]:
answers['8'] = 1478

In [24]:
data[data.revenue > data.budget]['imdb_id'].count()

1478

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [25]:
answers['9'] = 'The Dark Knight'

In [26]:
data_2008 = data[data.release_year==2008]
data_2008[data_2008.revenue == data_2008.revenue.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [27]:
answers['10'] = 'The Lone Ranger'

In [28]:
data_2012_2014 = data[(data.release_year>=2012) & (data.release_year<=2014)]
data_2012_2014[data_2012_2014.profit == data_2012_2014.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 11. Какого жанра фильмов больше всего?

In [29]:
answers['11'] = 'Drama'

In [30]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале

dict_genres = {}

for str_genre in data.genres:
    for genre in str_genre.split('|'):
        #print(genre)
        if genre in dict_genres:
            dict_genres[genre] = dict_genres[genre]+1
        else:
            dict_genres[genre] = 1

# Frequently genre in dataset            
often_genre = {k:v for k, v in dict_genres.items() if v == max(dict_genres.values())}
often_genre

{'Drama': 782}

ВАРИАНТ 2

In [31]:
cnt = Counter()

for str_genre in data.genres:
    for genre in str_genre.split('|'):
        #print(genre)
        if genre in dict_genres:
            cnt[genre] +=1
        else:
            cnt[genre] = 1

# Frequently genre in dataset            
cnt.most_common(1)

[('Drama', 782)]

ВАРИАНТ 3

In [32]:
genres  = data.genres
new_data = pd.DataFrame(genres.apply(lambda x: x.split("|")))
# Frequently genre in dataset
new_data.explode("genres").value_counts().head(1)

genres
Drama     782
dtype: int64

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [33]:
answers['12'] = 'Drama'

In [34]:
data = pd.read_csv('movie_bd_v5.csv')
data['profit'] = data['revenue'] - data['budget']
data['genres'] = data.genres.apply(lambda x: x.split("|"))
#display(data)
exdata = data.explode('genres')
exdata = exdata[exdata.profit > 0]
exdata.groupby('genres').size().sort_values(ascending=False)

genres
Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сбооры?

In [35]:
answers['13'] = 'Peter Jackson'

In [36]:
data = pd.read_csv('movie_bd_v5.csv')
data.groupby('director')['revenue'].sum().sort_values(ascending=False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 957, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [37]:
answers['14'] = 'Paul W.S. Anderson'

In [34]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['genres'] = data.genres.apply(lambda x: x.split("|"))
data['director'] = data.director.apply(lambda x: x.split("|"))
exdata = data.explode('genres')
exdata = exdata.explode('director')
exdata = exdata[exdata['genres']=='Action']
exdata.groupby('director').genres.count().sort_values(ascending=False)

director
Robert Rodriguez      9
Paul W.S. Anderson    7
Michael Bay           7
Ridley Scott          6
Antoine Fuqua         6
                     ..
Joe Cornish           1
Roger Spottiswoode    1
Jimmy Hayward         1
Jim Gillespie         1
Jon Avnet             1
Name: genres, Length: 364, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [39]:
answers['15'] = 'Scarlett Johansson'

In [52]:
data = pd.read_csv('movie_bd_v5.csv')
data['cast'] = data.cast.apply(lambda x: x.split("|"))
exdata = data.explode('cast')
exdata[exdata['release_year']==2012].groupby('cast').revenue.sum().sort_values(ascending=False)
#exdata['release_year'] = exdata[exdata['release_year']==2012]
#exdata.groupby('cast').revenue.max().sort_values(ascending= False)

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [41]:
answers['16'] = 'Matt Damon'

In [59]:
data = pd.read_csv('movie_bd_v5.csv')
data['cast'] = data.cast.apply(lambda x: x.split("|"))
exdata = data.explode('cast')
hbdata = exdata[exdata.budget >  exdata.budget.mean()]
hbdata.groupby('cast').budget.count().sort_values(ascending=False)

cast
Matt Damon           18
Adam Sandler         17
Angelina Jolie       16
Eddie Murphy         15
Samuel L. Jackson    15
                     ..
Leslie Bibb           1
Leonard Nimoy         1
Lennie James          1
Lena Olin             1
50 Cent               1
Name: budget, Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [43]:
answers['17'] = 'Action'

In [44]:
data = pd.read_csv('movie_bd_v5.csv')
data['cast'] = data.cast.apply(lambda x: x.split("|"))
data['genres'] = data.genres.apply(lambda x: x.split("|"))
exdata = data.explode('cast')
exdata = exdata.explode('genres')
exdata[exdata.cast == 'Nicolas Cage'].genres.value_counts()

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Animation           3
Mystery             3
Family              3
History             2
War                 1
Horror              1
Romance             1
Name: genres, dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures

In [45]:
answers['18'] = 'K-19: The Widowmaker'

In [60]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['profit'] = data['revenue'] - data['budget']
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
exdata = data.explode('production_companies')
ppdata = exdata[exdata.production_companies == 'Paramount Pictures']
ppdata[ppdata.profit == ppdata.profit.min()]
#& (exdata.profit == exdata.profit.min())

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures,7/19/2002,6.0,2002,-64831034

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [47]:
answers['19'] = 2015

In [62]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data.groupby('release_year').revenue.sum().sort_values(ascending= False)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [49]:
answers['20'] = 2014

In [81]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['profit'] = data['revenue'] - data['budget']
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
exdata = data.explode('production_companies')
exdata = exdata[exdata.production_companies.str.contains('Warner')]
exdata.groupby('release_year').profit.sum().sort_values(ascending=False)
#exdata = exdata[exdata.production_companies == 'Warner Bros. Pictures']
#exdata.groupby('release_year').profit.sum().sort_values(ascending=False)

release_year
2014    2292949646
2007    2208217007
2008    2134595031
2010    1974712985
2011    1871393682
2003    1844008221
2009    1822454136
2013    1636453400
2004    1631933725
2005    1595278228
2001    1282142579
2012    1258020056
2002    1022709901
2015     870368348
2006     622332868
2000     452631386
Name: profit, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [ ]:
answers['21'] = 9

In [113]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['month'] =  data.release_date.str.split("/").apply(lambda x: x[0])
data.groupby('month').size().sort_values(ascending=False)

month
9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [ ]:
answers['22'] = 450

In [203]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['month'] = data.release_date.str.split("/").apply(lambda x: x[0])
data.groupby('month').size().loc[['6','7','8']].sum()

450

# 23. Для какого режиссера зима – самое продуктивное время года?

In [ ]:
answers['23'] = 'Peter Jackson'

In [229]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['director'] = data.director.apply(lambda x: x.split("|"))
data = data.explode('director')
data['month'] =  data.release_date.str.split("/").apply(lambda x: x[0])
data = data.query('month == "12" | month == "1" | month == "2"')
data.groupby('director').size().sort_values(ascending=False)

director
Peter Jackson            7
Steven Soderbergh        6
Clint Eastwood           6
Martin Scorsese          4
Adam Shankman            4
                        ..
Matt Bettinelli-Olpin    1
Matt Reeves              1
Matthew O'Callaghan      1
Matthew Vaughn           1
Jon Avnet                1
Length: 358, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [ ]:
answers['24'] = 'Four By Two Productions'

In [243]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
data = data.explode('production_companies')
data['title_len'] = data['original_title'].apply(len)
data.groupby('production_companies').title_len.mean().sort_values(ascending=False)

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Polsky Films                  46.0
Museum Canada Productions     46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
XM2 Productions                2.0
Global Entertainment Group     2.0
Ixtlan Productions             2.0
Name: title_len, Length: 1771, dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [ ]:
answers['25'] = 'Midnight Picture Show'

In [250]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
data = data.explode('production_companies')
data['overview_len'] = data['overview'].apply(len)
data.groupby('production_companies').overview_len.mean().sort_values(ascending=False)

production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
Projection Pictures                        74.0
London Boulevard                           74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: overview_len, Length: 1771, dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [298]:
import pandas as pd
data = pd.read_csv('movie_bd_v5.csv')
data[data.vote_average > data.vote_average.quantile(0.99)].sort_values('vote_average',ascending=False)
#data.groupby("vote_average").original_title.value_counts()

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015
34,tt3170832,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015
118,tt0816692,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014
125,tt2084970,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014
119,tt2015381,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014
128,tt2267998,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014
138,tt2278388,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014
370,tt1375666,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010
872,tt0253474,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003
1183,tt0993846,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013
1191,tt2024544,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013
1800,tt0209144,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [490]:
from itertools import combinations
import pandas as pd

def cast_combination(data):
    cast_list = []
    for pair in combinations(data,2):
        cast_list.append(list(pair))
    return cast_list

data = pd.read_csv('movie_bd_v5.csv')
data['cast'] = data.cast.apply(lambda x: x.split("|"))
data['cast'] = data.cast.apply(cast_combination)
data = data.explode('cast')
data['cast'] = data.cast.apply(lambda x: str(x))
data.cast.value_counts().sort_values(ascending=False)

['Daniel Radcliffe', 'Rupert Grint']       8
['Daniel Radcliffe', 'Emma Watson']        8
['Rupert Grint', 'Emma Watson']            7
['Johnny Depp', 'Helena Bonham Carter']    6
['Ben Stiller', 'Owen Wilson']             6
                                          ..
['Russell Brand', 'Jennifer Garner']       1
['Dennis Quaid', 'Cung Le']                1
['Kirsten Dunst', 'Joanna Lumley']         1
['Seth Green', 'John Malkovich']           1
['Helen Mirren', 'Julie Walters']          1
Name: cast, Length: 18122, dtype: int64

ВАРИАНТ 2

# Submission

In [51]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': 'Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': 'Gods and Generals',
 '3': 'Winnie the Pooh',
 '4': 109.6585494970884,
 '5': 107.0,
 '6': 'Avatar',
 '7': 'The Lone Ranger',
 '8': 1478,
 '9': 'The Dark Knight',
 '10': 'The Lone Ranger',
 '11': 'Drama',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '14': 'Paul W.S. Anderson',
 '15': 'Scarlett Johansson',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker',
 '19': 2015,
 '20': 2007}

In [52]:
# и убедиться что ни чего не пропустил)
len(answers)

20