In [2369]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [2370]:
data = pd.read_csv('movie_bd_v5.csv')
data.head(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015
1,tt1392190,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,7.1,2015
2,tt2908446,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,6.3,2015
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015

In [2371]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

In [2372]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1889 entries, 0 to 1888
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   imdb_id               1889 non-null   object
 1   budget                1889 non-null   int64
 2   revenue               1889 non-null   int64
 3   original_title        1889 non-null   object
 4   cast                  1889 non-null   object
 5   director              1889 non-null   object
 6   tagline               1889 non-null   object
 7   overview              1889 non-null   object
 8   runtime               1889 non-null   int64
 9   genres                1889 non-null   object
 10  production_companies  1889 non-null   object
 11  release_date          1889 non-null   object
 12  vote_average          1889 non-null   float64
 13  release_year          1889 non-null   int64
dtypes: float64(1), int64(4), object(9)
memory usage: 206.7+ KB

# Предобработка

In [2373]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

# Adding  new column - Profit
data['profit'] = data['revenue'] - data['budget']


#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

#function to combine all cast each movie by pairs
def cast_combination(data):
    cast_list = []
    for pair in combinations(data,2):
        cast_list.append(list(pair))
    return cast_list

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [2374]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)'
# если ответили верно, можете добавить комментарий со значком "+"

In [2375]:
# тут пишем ваш код для решения данного вопроса:
q1_data = data
q1_data[q1_data['budget']==q1_data['budget'].max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011,641683000

ВАРИАНТ 2

In [2376]:
# можно добавлять разные варианты решения

# 2. Какой из фильмов самый длительный (в минутах)?

In [2377]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals'

In [2378]:
q2_data = data
q2_data[q2_data.runtime == q2_data.runtime.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003,-43076064

# 3. Какой из фильмов самый короткий (в минутах)?

In [2379]:
answers['3'] = 'Winnie the Pooh'

In [2380]:
q3_data = data
q3_data[q3_data.runtime == q3_data.runtime.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011,-15540000

# 4. Какова средняя длительность фильмов?

In [2381]:
answers['4'] = 109.6585494970884

#### ВАРИАНТ 1

In [2382]:
q4_data = data
q4_data.runtime.mean()

109.6585494970884

#### ВАРИАНТ 2

In [2383]:
q4_data.describe()['runtime']['mean']

109.6585494970884

# 5. Каково медианное значение длительности фильмов?

In [2384]:
answers['5'] = 107.0

In [2385]:
q5_data = data
q5_data['runtime'].median()

107.0

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [2386]:
answers['6'] = 'Avatar'

In [2387]:
# лучше код получения столбца profit вынести в Предобработку что в начале
q6_data = data
q6_data[q6_data.profit == q6_data.profit.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

# 7. Какой фильм самый убыточный?

In [2388]:
answers['7'] = 'The Lone Ranger'

In [2389]:
q7_data = data
q7_data[q7_data.profit == q7_data.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [2390]:
answers['8'] = 1478

In [2391]:
q8_data = data
q8_data[q8_data.revenue > q8_data.budget]['imdb_id'].count()

1478

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [2392]:
answers['9'] = 'The Dark Knight'

In [2393]:
q9_data = data
q9_data = q9_data[q9_data.release_year==2008]
q9_data[q9_data.revenue == q9_data.revenue.max()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008,816921825

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [2394]:
answers['10'] = 'The Lone Ranger'

In [2395]:
q10_data = data
q10_data = q10_data[(q10_data.release_year>=2012) & (q10_data.release_year<=2014)]
q10_data[q10_data.profit == q10_data.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 11. Какого жанра фильмов больше всего?

In [2396]:
answers['11'] = 'Drama'

In [2397]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале
q11_data = data

dict_genres = {}

# Create dictionary of genres
for str_genre in q11_data.genres:
    for genre in str_genre.split('|'):
        #print(genre)
        if genre in dict_genres:
            dict_genres[genre] = dict_genres[genre]+1
        else:
            dict_genres[genre] = 1

# Frequently genre in dataset            
often_genre = {k:v for k, v in dict_genres.items() if v == max(dict_genres.values())}
often_genre

{'Drama': 782}

ВАРИАНТ 2

In [2398]:
cnt = Counter()

# We also can use Counter to make Dictionary
for str_genre in q11_data.genres:
    for genre in str_genre.split('|'):
        #print(genre)
        if genre in dict_genres:
            cnt[genre] +=1
        else:
            cnt[genre] = 1

# Frequently genre in dataset using properties of Counter lib
cnt.most_common(1)

[('Drama', 782)]

ВАРИАНТ 3

In [2399]:
genres  = q11_data.genres
new_data = pd.DataFrame(genres.apply(lambda x: x.split("|")))
# Frequently genre in dataset
new_data.explode("genres").value_counts().head(1)

genres
Drama     782
dtype: int64

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [2400]:
answers['12'] = 'Drama'

In [2401]:
q12_data = data
# To make divided by genres
q12_data['genres'] = q12_data.genres.apply(lambda x: x.split("|"))
#Unroll list data using explode function
exdata = q12_data.explode('genres')
exdata = exdata[exdata.profit > 0]
exdata.groupby('genres').size().sort_values(ascending=False)

genres
Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сбооры?

In [2402]:
answers['13'] = 'Peter Jackson'

In [2403]:
q13_data = data
q13_data.groupby('director')['revenue'].sum().sort_values(ascending=False)

director
Peter Jackson        6490593685
Christopher Nolan    4167548502
David Yates          4154295625
Michael Bay          3886938960
J.J. Abrams          3579169916
                        ...
David MichÃ´d           2295423
Steven Shainberg        2281089
Paul Schrader           2062066
Keanu Reeves            2054941
Simon Hunter            2033165
Name: revenue, Length: 957, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [2404]:
answers['14'] = 'Robert Rodriguez'

In [2405]:
data = pd.read_csv('movie_bd_v5.csv')
q14_data = data
# To make divided by genres and directors
q14_data['genres'] = q14_data.genres.apply(lambda x: x.split("|"))
q14_data['director'] = q14_data.director.apply(lambda x: x.split("|"))
#Unroll list data using explode function
exdata = q14_data.explode('genres')
exdata = exdata.explode('director')
#looking for Action genre
exdata = exdata[exdata['genres']=='Action']
exdata.groupby('director').genres.count().sort_values(ascending=False)

director
Robert Rodriguez      9
Paul W.S. Anderson    7
Michael Bay           7
Ridley Scott          6
Antoine Fuqua         6
                     ..
Joe Cornish           1
Roger Spottiswoode    1
Jimmy Hayward         1
Jim Gillespie         1
Jon Avnet             1
Name: genres, Length: 364, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [2406]:
answers['15'] = 'Chris Hemsworth'

In [2407]:
q15_data = data
q15_data['cast'] = q15_data.cast.apply(lambda x: x.split("|"))
exdata = q15_data.explode('cast')
exdata[exdata['release_year']==2012].groupby('cast').revenue.sum().sort_values(ascending=False)

cast
Chris Hemsworth      2027450773
Denis Leary          1629460639
Anne Hathaway        1522851057
Chris Evans          1519557910
Robert Downey Jr.    1519557910
                        ...
Jason Bateman           3428048
Danny Huston            2106557
Sami Gayle              2106557
Josh Lucas              2106557
Nicolas Cage            2106557
Name: revenue, Length: 466, dtype: int64

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [2408]:
answers['16'] = 'Matt Damon'

In [2409]:
data = pd.read_csv('movie_bd_v5.csv')
q16_data = data
q16_data['cast'] = q16_data.cast.apply(lambda x: x.split("|"))
exdata = q16_data.explode('cast')
exdata = exdata[exdata.budget >  exdata.budget.mean()]
exdata.groupby('cast').budget.count().sort_values(ascending=False)

cast
Matt Damon           18
Adam Sandler         17
Angelina Jolie       16
Eddie Murphy         15
Samuel L. Jackson    15
                     ..
Leslie Bibb           1
Leonard Nimoy         1
Lennie James          1
Lena Olin             1
50 Cent               1
Name: budget, Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [2410]:
answers['17'] = 'Action'

In [2411]:
data = pd.read_csv('movie_bd_v5.csv')
q17_data = data
q17_data['cast'] = q17_data.cast.apply(lambda x: x.split("|"))
q17_data['genres'] = q17_data.genres.apply(lambda x: x.split("|"))
exdata = q17_data.explode('cast')
exdata = exdata.explode('genres')
exdata[exdata.cast == 'Nicolas Cage'].genres.value_counts()

Action             17
Thriller           15
Drama              12
Crime              10
Fantasy             8
Adventure           7
Comedy              6
Science Fiction     4
Mystery             3
Family              3
Animation           3
History             2
Horror              1
War                 1
Romance             1
Name: genres, dtype: int64

# 18. Самый убыточный фильм от Paramount Pictures

In [2412]:
answers['18'] = 'K-19: The Widowmaker'

In [2413]:
data = pd.read_csv('movie_bd_v5.csv')
data['profit'] = data['revenue'] - data['budget']
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
exdata = data.explode('production_companies')
ppdata = exdata[exdata.production_companies == 'Paramount Pictures']
ppdata[ppdata.profit == ppdata.profit.min()]

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures,7/19/2002,6.0,2002,-64831034

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [2414]:
answers['19'] = 2015

In [2415]:
data.groupby('release_year').revenue.sum().sort_values(ascending= False)

release_year
2015    25449202382
2014    23405862953
2013    23213799791
2012    23079001687
2011    22676791872
2010    21071204961
2009    20261791024
2008    18252781990
2007    18162406801
2004    15663430720
2005    15309425558
2006    14775042320
2003    14346123312
2002    14136361487
2001    13017764865
2000    10664099805
Name: revenue, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [2416]:
answers['20'] = 2014

In [2417]:
data = pd.read_csv('movie_bd_v5.csv')
data['profit'] = data['revenue'] - data['budget']
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
exdata = data.explode('production_companies')
exdata = exdata[exdata.production_companies.str.contains('Warner')]
exdata.groupby('release_year').profit.sum().sort_values(ascending=False)

release_year
2014    2292949646
2007    2208217007
2008    2134595031
2010    1974712985
2011    1871393682
2003    1844008221
2009    1822454136
2013    1636453400
2004    1631933725
2005    1595278228
2001    1282142579
2012    1258020056
2002    1022709901
2015     870368348
2006     622332868
2000     452631386
Name: profit, dtype: int64

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [2418]:
answers['21'] = 9

In [2419]:
data['month'] =  data.release_date.str.split("/").apply(lambda x: x[0])
data.groupby('month').size().sort_values(ascending=False)

month
9     227
12    190
10    186
8     161
3     156
4     149
6     147
11    146
7     142
5     140
2     135
1     110
dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [2420]:
answers['22'] = 450

In [2421]:
data['month'] = data.release_date.str.split("/").apply(lambda x: x[0])
#Using loc method to choose only 3 months of summer
data.groupby('month').size().loc[['6','7','8']].sum()

450

# 23. Для какого режиссера зима – самое продуктивное время года?

In [2422]:
answers['23'] = 'Peter Jackson'

In [2423]:
newdata = data
newdata['director'] = newdata.director.apply(lambda x: x.split("|"))
newdata = newdata.explode('director')
#Split date by delimeter and choose a month from it
newdata['month'] =  newdata.release_date.str.split("/").apply(lambda x: x[0])
newdata = newdata.query('month == "12" | month == "1" | month == "2"')
newdata.groupby('director').size().sort_values(ascending=False)

director
Peter Jackson            7
Steven Soderbergh        6
Clint Eastwood           6
Martin Scorsese          4
Adam Shankman            4
                        ..
Matt Bettinelli-Olpin    1
Matt Reeves              1
Matthew O'Callaghan      1
Matthew Vaughn           1
Jon Avnet                1
Length: 358, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [2424]:
answers['24'] = 'Four By Two Productions'

In [2425]:
data = pd.read_csv('movie_bd_v5.csv')
q24_data = data
q24_data['production_companies'] = q24_data.production_companies.apply(lambda x: x.split("|"))
q24_data = q24_data.explode('production_companies')
q24_data['title_len'] = q24_data['original_title'].apply(len)
q24_data.groupby('production_companies').title_len.mean().sort_values(ascending=False)

production_companies
Four By Two Productions       83.0
Jim Henson Company, The       59.0
Dos Corazones                 47.0
Museum Canada Productions     46.0
Polsky Films                  46.0
                              ...
Everest Entertainment          3.0
Berlanti Productions           3.0
XM2 Productions                2.0
Ixtlan Productions             2.0
Global Entertainment Group     2.0
Name: title_len, Length: 1771, dtype: float64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [2426]:
answers['25'] = 'Midnight Picture Show'

In [2427]:
data = pd.read_csv('movie_bd_v5.csv')
data['production_companies'] = data.production_companies.apply(lambda x: x.split("|"))
data = data.explode('production_companies')
data['overview_len'] = data['overview'].apply(len)
data.groupby('production_companies').overview_len.mean().sort_values(ascending=False)

production_companies
Midnight Picture Show                    1000.0
Room 9 Entertainment                      964.0
Brookwell-McNamara Entertainment          936.0
Lions Gate Family Entertainment           909.0
Crest Animation Productions               909.0
                                          ...
Projection Pictures                        74.0
London Boulevard                           74.0
Phantom Four                               72.0
Empire Pictures                            62.0
Motion Picture Corporation of America      59.0
Name: overview_len, Length: 1771, dtype: float64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [2428]:
answers['26'] = 'The Dark Knight, Inside Out, 12 Years a Slave'

In [2429]:
data = pd.read_csv('movie_bd_v5.csv')
#Using special method in Pandas
best = data[data.vote_average > data.vote_average.quantile(0.99)].sort_values('vote_average',ascending=False)
best.original_title

599                                   The Dark Knight
9                                          Inside Out
34                                               Room
118                                      Interstellar
125                                The Imitation Game
119                           Guardians of the Galaxy
128                                         Gone Girl
138                          The Grand Budapest Hotel
370                                         Inception
872                                       The Pianist
1081    The Lord of the Rings: The Return of the King
1183                          The Wolf of Wall Street
1191                                 12 Years a Slave
1800                                          Memento
Name: original_title, dtype: object

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [2430]:
answers['27'] = ['Daniel Radcliffe', 'Rupert Grint']

In [2431]:
data = pd.read_csv('movie_bd_v5.csv')
data['cast'] = data.cast.apply(lambda x: x.split("|"))

#aplly own function for combine all cast by pairs
data['cast'] = data.cast.apply(cast_combination)
data = data.explode('cast')
data['cast'] = data.cast.apply(lambda x: str(x))
data.cast.value_counts().sort_values(ascending=False)

['Daniel Radcliffe', 'Rupert Grint']             8
['Daniel Radcliffe', 'Emma Watson']              8
['Rupert Grint', 'Emma Watson']                  7
['Ben Stiller', 'Owen Wilson']                   6
['Johnny Depp', 'Helena Bonham Carter']          6
                                                ..
['Michael-Leon Wooley', 'Jennifer Cody']         1
['Stephen Baldwin', 'Joan Collins']              1
['Jason Bateman', 'Leslie Mann']                 1
['Rosanna Arquette', 'Michael Clarke Duncan']    1
['Kevin James', 'Vince Vaughn']                  1
Name: cast, Length: 18122, dtype: int64

ВАРИАНТ 2

# Submission

In [2432]:
# в конце можно посмотреть свои ответы к каждому вопросу
answers

{'1': 'Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': 'Gods and Generals',
 '3': 'Winnie the Pooh',
 '4': 109.6585494970884,
 '5': 107.0,
 '6': 'Avatar',
 '7': 'The Lone Ranger',
 '8': 1478,
 '9': 'The Dark Knight',
 '10': 'The Lone Ranger',
 '11': 'Drama',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '14': 'Robert Rodriguez',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '18': 'K-19: The Widowmaker',
 '19': 2015,
 '20': 2014,
 '21': 9,
 '22': 450,
 '23': 'Peter Jackson',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show',
 '26': 'The Dark Knight, Inside Out, 12 Years a Slave',
 '27': ['Daniel Radcliffe', 'Rupert Grint']}

In [2433]:
# и убедиться что ни чего не пропустил)
len(answers)

27